feat(home-manager): init console module
Stonks3141/ctp-nix pull request #69
Opened 2024-01-08 20:49 UTC by Anomalocaridid

Add module for theming the tty. Resolves #12.

It uses the colors from [catppuccin/tty](https://github.com/catppuccin/tty), but I had to bring in [catppuccin/palette](https://github.com/catppuccin/palette) and parse `palette.json`. Also they appear to have gotten rid of the separate `palette-porcelain.json` file.

2024-01-11 22:01 UTC, getchoo requested changes

2024-01-11 22:01 UTC, getchoo commented on modules/nixos/console.nix
> +  palette = (fromJSON (readFile (sources.palette + /palette.json))).${cfg.flavour}.colors;
nitpick :p 
```suggestion
  cfg = config.console.catppuccin;
  enable = cfg.enable && config.console.enable;
  palette = (lib.importJSON "${sources.palette}/palette.json").${cfg.flavour}.colors;
```

2024-01-11 22:01 UTC, getchoo commented on modules/nixos/console.nix
> +    map (color: (substring 1 6 palette.${color}.hex)) [
```suggestion
    map (color: (builtins.substring 1 6 palette.${color}.hex)) [
```

2024-02-08 02:46 UTC, Anomalocaridid commented
I just realized I probably should have said something when I made the changes you requested to let you know they were ready to be looked at. Sorry about that.

2024-03-13 22:04 UTC, getchoo commented
all good, and sorry for the long review time lol

this works great! thanks :)

2024-03-13 22:04 UTC, getchoo approved these changes

2024-03-13 22:04 UTC, merged